# Generated by Django 2.1.7 on 2019-05-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, db_column='ID', max_length=20, null=True)),
                ('pw', models.CharField(blank=True, db_column='PW', max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainapp.User')),
                ('name', models.CharField(max_length=50)),
                ('lastupdatetime', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fileinfo',
                'managed': False,
            },
        ),
    ]
