# Generated by Django 2.1.7 on 2019-05-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filelists',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('lastupdatetime', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'filelists',
                'managed': False,
            },
        ),
    ]
