# Generated by Django 2.1.7 on 2019-05-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_filelists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filelists',
            options={'managed': True},
        ),
    ]
