# Generated by Django 2.1.7 on 2019-05-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190514_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelists',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=123, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.User'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='filelists',
            unique_together={('uid', 'name')},
        ),
    ]
